### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by InputUsername** [treeshateorcs/listenbrainz-rust#1]
Currently, whenever a Reqwest request fails, for example due to a network error, this error is simply unwrapped, which causes panics. Also `Err` results from functions only contain the string `"error"`, which makes it difficult to diagnose what's wrong.

**Comment by treeshateorcs** [comment]
please take a look I think I've fixed it

**Comment by InputUsername** [comment]
Looks good, I will update the dependency in rescrobbled soon.

What about the `Err("error".into())` case? It maybe useful to notify users
of the library if they're passing wrong arguments.

**Comment by treeshateorcs** [comment]
I'm not sure i'm doing it right

**Comment by InputUsername** [comment]
I think it looks good now, thanks for the quick fixes!
